Phone_Ecommerce_Manage/Models/Rom.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Phone_Ecommerce_Manage.Models
{
    [Table("ROM")]
    public partial class Rom
    {
        public Rom()
        {
            ProductVersions = new HashSet<ProductVersion>();
        }

        [Key]
        [Column("IdROM")]
        public int IdRom { get; set; }
        [Column("NameROM")]
        [StringLength(10)]
        public string NameRom { get; set; } = null!;

        [InverseProperty("IdRomNavigation")]
        public virtual ICollection<ProductVersion> ProductVersions { get; set; }
    }
}

Phone_Ecommerce_Manage/Areas/Admin/Controllers/RomsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Phone_Ecommerce_Manage.Models;

namespace Phone_Ecommerce_Manage.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin, Employee")]
    public class RomsController : Controller
    {
        private readonly MobileShop_DBContext _context;

        public RomsController(MobileShop_DBContext context)
        {
            _context = context;
        }

        // GET: Admin/Roms
        public async Task<IActionResult> Index()
        {
              return View(await _context.Roms.ToListAsync());
        }

        // GET: Admin/Roms/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Roms == null)
            {
                return NotFound();
            }

            var rom = await _context.Roms
                .FirstOrDefaultAsync(m => m.IdRom == id);
            if (rom == null)
            {
                return NotFound();
            }

            return View(rom);
        }

        // GET: Admin/Roms/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/Roms/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdRom,NameRom")] Rom rom)
        {
            if (ModelState.IsValid)
            {
                _context.Add(rom);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(rom);
        }

        // GET: Admin/Roms/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Roms == null)
            {
                return NotFound();
            }

            var rom = await _context.Roms.FindAsync(id);
            if (rom == null)
            {
                return NotFound();
            }
            return View(rom);
        }

        // POST: Admin/Roms/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdRom,NameRom")] Rom rom)
        {
            if (id != rom.IdRom)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(rom);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RomExists(rom.IdRom))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(rom);
        }

        // GET: Admin/Roms/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Roms == null)
            {
                return NotFound();
            }

            var rom = await _context.Roms
                .FirstOrDefaultAsync(m => m.IdRom == id);
            if (rom == null)
            {
                return NotFound();
            }

            return View(rom);
        }

        // POST: Admin/Roms/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Roms == null)
            {
                return Problem("Entity set 'MobileShop_DBContext.Roms'  is null.");
            }
            var rom = await _context.Roms.FindAsync(id);
            if (rom != null)
            {
                _context.Roms.Remove(rom);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RomExists(int id)
        {
          return _context.Roms.Any(e => e.IdRom == id);
        }
    }
}

Phone_Ecommerce_Manage/Areas/Admin/Views/Roms/Create.cshtml
@model Phone_Ecommerce_Manage.Models.Rom

@{
    ViewData["Title"] = "Thêm dung lượng bộ nhớ";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="login-wrap d-flex align-items-center flex-wrap justify-content-center">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-md-6 col-lg-7">
                <img src="~/adminasset/vendors/images/register-page-img.png" alt="" />
            </div>
            <div class="col-md-6 col-lg-5">
                <div class="login-box bg-white box-shadow border-radius-10">
                    <div class="login-title">
                        <h2 class="text-center text-primary">Thêm dung lượng bộ nhớ</h2>
                    </div>
                    <form asp-action="Create">
                        <label asp-for="NameRom"><h6>Tên dung lượng bộ nhớ</h6></label>
                        <div class="input-group custom">
                            <input asp-for="NameRom" class="form-control form-control-lg"
                                   type="text" />
                        </div>
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="input-group mb-0">
                                    <input type="submit" value="Lưu" class="btn btn-primary btn-lg btn-block" />
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="main-container">
    <div class="pd-ltr-20 xs-pd-20-10">
        <div class="min-height-200px">
            <div class="pd-20 card-box mb-30">
                <div class="clearfix mb-30">
                    <div class="pull-left">
                        <h4 class="text-blue h4">Thêm RAM</h4>
                    </div>
                </div>
                <form asp-action="Create">
                    <div class="form-group row">
                        <label asp-for="NameRom" class="col-sm-12 col-md-2 col-form-label">Tên màu</label>
                        <div class="col-sm-12 col-md-10">
                            <input asp-for="NameRom" class="form-control"
                                   type="text" />
                        </div>
                    </div>
                    <div class="clearfix">
                        <div class="pull-right">
                            <div class="form-group">
                                <input type="submit" value="Lưu" class="btn btn-primary btn-sm scroll-click" />
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

Phone_Ecommerce_Manage/Areas/Admin/Views/Roms/Delete.cshtml
@model Phone_Ecommerce_Manage.Models.Rom

@{
    ViewData["Title"] = "Xoá dung lượng bộ nhớ";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="login-wrap d-flex align-items-center flex-wrap justify-content-center">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-md-6 col-lg-7">
                <img src="~/adminasset/vendors/images/register-page-img.png" alt="" />
            </div>
            <div class="col-md-6 col-lg-5">
                <div class="login-box bg-white box-shadow border-radius-10">
                    <div class="login-title">
                        <h2 class="text-center text-primary">Xoá dung lượng bộ nhớ</h2>
                    </div>
                    <form asp-action="Delete">
                        <label asp-for="NameRom"><h6>Tên dung lượng bộ nhớ</h6></label>
                        <div class="input-group custom">
                            <input asp-for="NameRom" class="form-control form-control-lg"
                                   type="text" />
                        </div>
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="input-group mb-0">
                                    <input type="hidden" asp-for="IdRom" />
                                    <input type="submit" value="Xoá" class="btn btn-danger" /> &ensp;
                                    <a asp-action="Index" class="btn btn-primary">Quay lại danh sách</a>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

Phone_Ecommerce_Manage/Areas/Admin/Views/Roms/Edit.cshtml
@model Phone_Ecommerce_Manage.Models.Rom

@{
    ViewData["Title"] = "Chỉnh sửa dung lượng bộ nhớ";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="login-wrap d-flex align-items-center flex-wrap justify-content-center">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-md-6 col-lg-7">
                <img src="~/adminasset/vendors/images/register-page-img.png" alt="" />
            </div>
            <div class="col-md-6 col-lg-5">
                <div class="login-box bg-white box-shadow border-radius-10">
                    <div class="login-title">
                        <h2 class="text-center text-primary">Cập nhật dung lượng bộ nhớ</h2>
                    </div>
                    <form asp-action="Edit">
                        <label asp-for="NameRom"><h6>Dung lượng bộ nhớ</h6></label>
                        <input type="hidden" asp-for="IdRom" />
                        <div class="input-group custom">
                            <input asp-for="NameRom" class="form-control form-control-lg"
                                   type="text" />
                        </div>
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="input-group mb-0">
                                    <input type="submit" value="Lưu" class="btn btn-outline-primary" /> &ensp;
                                    <a class="btn btn-outline-danger" asp-action="Index">Quay lại danh sách</a>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

Phone_Ecommerce_Manage/Areas/Admin/Views/Roms/Index.cshtml
@model IEnumerable<Phone_Ecommerce_Manage.Models.Rom>

@{
    ViewData["Title"] = "Danh sách dung lượng bộ nhớ";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="main-container">
    <div>
        <div class="min-height-200px">
            <div class="card-box mb-30">
                <div class="pd-20">
                    <h4 class="text-blue h4">Danh sách dung lượng bộ nhớ</h4>
                    <a asp-area="Admin" asp-controller="Roms" asp-action="Create" type="button" class="btn btn-primary">
                        Thêm dung lượng bộ nhớ
                    </a>
                </div>
                <div class="pb-20">
                    <table class="data-table table stripe hover nowrap">
                        <thead>
                            <tr>
                                <th>Dung lượng bộ nhớ</th>
                                <th class="table-plus datatable-nosort"></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>@item.NameRom</td>
                                    <td>
                                        <a asp-action="Edit" asp-route-id="@item.IdRom" class="btn btn-primary">Sửa</a>
                                        <a asp-action="Delete" asp-route-id="@item.IdRom" class="btn btn-danger">Xóa</a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>